# Site settings
title: Blog
url: "http://vincentliaw.me/blog"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave blank to disable it
google_analytics: 
disqus_shortname: 
